import Link from "next/link";
import { ArrowUpRight, Bell, Box, Building2, CircleHelp, FileText, MapPin, Package, RefreshCw } from "lucide-react";

const gold = "#c99d54";

export default function DashboardPage() {
  return (
    <div className="mx-auto max-w-[1440px] text-[#4f5967]">
      <section className="relative overflow-hidden rounded-xl bg-[linear-gradient(110deg,#c99d54,#a6782d)] px-6 py-5 text-white shadow-sm">
        <div className="absolute -right-7 -top-11 h-36 w-36 rounded-full bg-white/15" />
        <p className="relative text-xs">Fri, 17 July 2026</p>
        <h1 className="relative mt-1 text-[28px] font-semibold leading-none">Welcome Back!</h1>
        <p className="relative mt-3 text-xs">BIO WORLD TRADERS — 873 documents · 41 awaiting post</p>
        <div className="absolute bottom-5 right-5 flex gap-2"><Link href="/dashboard/sales/create-invoice" className="rounded-md bg-white px-3 py-2 text-[11px] font-medium text-[#5d5750]">New Sales Invoice <ArrowUpRight className="inline h-3 w-3" /></Link><button className="rounded-md bg-white px-3 py-2 text-[11px] text-[#5d5750]">View Reports</button><button className="rounded-md bg-white px-3 py-2 text-[11px] text-[#5d5750]"><RefreshCw className="inline h-3 w-3" /> Refresh data</button></div>
      </section>

      <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_280px]">
        <div className="space-y-4">
          <DashboardSection title="Sales"><div className="grid gap-2 sm:grid-cols-2"><SummaryCard title="Sales Invoices" count="11" /><SummaryCard title="Sales Returns" count="0" returnCard /></div></DashboardSection>
          <DashboardSection title="Purchases"><div className="grid gap-2 sm:grid-cols-2"><SummaryCard title="Sales Invoices" count="11" /><SummaryCard title="Purchase Returns" count="0" returnCard /></div></DashboardSection>
          <DashboardSection title="Inventory"><div className="grid gap-2 sm:grid-cols-2"><SummaryCard title="Inventory Adjustments" count="11" inventory /><SummaryCard title="Inventory Adjustments" count="11" inventory /></div></DashboardSection>
          <section><p className="mb-1 text-[9px] font-medium">Company Profile</p><div className="rounded-[8px] border border-[#e6e7e9] bg-white p-2 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><div className="flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded-[5px] bg-[linear-gradient(135deg,#c99d54,#8a6221)] text-[8px] text-white">ES</span><div><b className="text-[9px]">BIO Encova Solution</b><p className="text-[7px] text-[#a3aab3]">Enterprise Resource Planning Account</p></div></div><div className="mt-2 grid gap-1.5 sm:grid-cols-2"><ProfileItem icon={Building2} label="Company ID" value="BWTR" /><ProfileItem icon={Bell} label="NTN" value="AT73964" /><ProfileItem icon={MapPin} label="Province" value="KPK" /><ProfileItem icon={MapPin} label="City" value="Khyber Pakhtunkhwa" /><ProfileItem icon={Box} label="Sandbox" value="Yes" /><ProfileItem icon={Package} label="License Expiry" value="2028-11-19" /></div></div></section>
        </div>
        <aside className="space-y-3"><SideStat title="Customers" value="209" label="Total registered customers" /><SideStat title="Items in Inventory" value="237" label="Products: 9  ·  Services: 228" /><Workload /><Activity /><MasterData /><Tips /></aside>
      </div>
    </div>
  );
}

function DashboardSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><p className="mb-2 text-sm font-semibold text-[#3f4854]">{title}</p>{children}</section>; }
function SummaryCard({ title, count, returnCard, inventory }: { title: string; count: string; returnCard?: boolean; inventory?: boolean }) { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#f5ead7] text-[#b88735]">{inventory ? <Box className="h-3.5 w-3.5" /> : <FileText className="h-3.5 w-3.5" />}</span>{title}</span><b className="text-sm">{count}</b></div><div className="mt-4 grid grid-cols-2 gap-2"><Status title="Posted" value={returnCard ? "11" : "11"} active /><Status title="Unposted" value="0" /></div></div>; }
function Status({ title, value, active }: { title: string; value: string; active?: boolean }) { return <div className="rounded-md bg-[#d4ad68] px-2.5 py-2 text-[10px] text-[#4d422f]"><div className="flex justify-between"><span>{title}</span><b>{value}</b></div><span className="mt-1.5 inline-block rounded-full bg-white px-2 py-0.5 text-[9px]">{active ? "Active" : "Pending"}</span></div>; }
function SideStat({ title, value, label }: { title: string; value: string; label: string }) { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><div className="flex justify-between text-[11px]"><span>{title}</span><ArrowUpRight className="h-3 w-3" /></div><b className="mt-2 block text-[28px] leading-none text-[#222b34]">{value}</b><p className="mt-2 text-[10px] text-[#9fa6ae]">{label}</p></div>; }
function Workload() { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><p className="text-xs font-semibold">Workload Split</p><div className="mt-3 flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-full border-[8px] border-[#d4ad68] text-[11px] font-semibold">859</div><div className="flex-1 space-y-2 text-[10px]"><p><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#c99d54]" />Posted docs <b className="float-right">812</b></p><p><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#e8e2d9]" />Unposted docs <b className="float-right">47</b></p></div></div></div>; }
function Activity() { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><p className="text-xs font-semibold">Activity Trend</p><div className="mt-3 flex h-20 items-end gap-1 rounded-md bg-[linear-gradient(180deg,transparent,#f3ecdf)] px-2">{[17,25,22,35,28,42,38,51,49].map((h, i) => <span key={i} className="flex-1 rounded-t bg-[#c99d54]/45" style={{ height: `${h}%` }} />)}</div><p className="mt-2 text-[9px] text-[#a3aab3]">Sales Invoices &nbsp; Purchase Invoices &nbsp; Returns</p></div>; }
function MasterData() { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><p className="text-xs font-semibold">Master Data</p>{[["Customer","45%"],["Vendors","82%"],["Items","56%"]].map(([name, val]) => <div key={name} className="mt-3 text-[10px]"><div className="flex justify-between"><span>{name}</span><b>{val}</b></div><div className="mt-1.5 h-1 rounded bg-[#eee]" style={{ background: `linear-gradient(90deg,${gold} ${val},#eee ${val})` }} /></div>)}</div>; }
function Tips() { return <div className="rounded-xl border border-[#e8e9eb] bg-white p-4 shadow-[0_1px_3px_rgba(0,0,0,.04)]"><p className="flex items-center gap-1.5 text-xs font-semibold"><CircleHelp className="h-3.5 w-3.5" />Quick Tips</p><ul className="mt-3 space-y-2.5 text-[10px] leading-relaxed text-[#747e8a]"><li>Use bulk Actions list pages to post or delete multiple documents.</li><li>Run detail and summary reports from the Reports section.</li><li>Keep your company ERP data updated under Company Profile.</li><li>Use Master Import to upload customers, items, and sales invoices in one go.</li></ul></div>; }
function ProfileItem({ icon: Icon, label, value }: { icon: typeof Building2; label: string; value: string }) { return <div className="flex items-center gap-2 rounded-md bg-[#f8f2e8] px-3 py-2.5"><Icon className="h-4 w-4 text-[#c99d54]" /><div><p className="text-[10px]">{label}</p><p className="text-[10px] text-[#bd8b38]">{value}</p></div></div>; }
